CREATE TABLE IF NOT EXISTS analytics.dim_identity
(
    identity_key BIGINT GENERATED ALWAYS AS IDENTITY,
    LIKE staging.raw_identity
);

COMMENT ON TABLE analytics.dim_identity IS
'Phase 4 analytical identity dimension. Grain: one row per available identity record associated with a transaction.';

COMMENT ON COLUMN analytics.dim_identity.identity_key IS
'Surrogate analytical primary key. Generated by PostgreSQL; does not replace TransactionID.';
