CREATE TABLE IF NOT EXISTS analytics.fact_transaction
(
    transaction_key BIGINT GENERATED ALWAYS AS IDENTITY,
    identity_key BIGINT NULL,
    LIKE staging.raw_transactions
);

COMMENT ON TABLE analytics.fact_transaction IS
'Phase 4 analytical transaction fact. Grain: one row per source transaction identified by TransactionID.';

COMMENT ON COLUMN analytics.fact_transaction.transaction_key IS
'Surrogate analytical primary key. Generated by PostgreSQL; does not replace TransactionID.';

COMMENT ON COLUMN analytics.fact_transaction.identity_key IS
'Nullable surrogate foreign key to dim_identity. Identity information is optional for a transaction.';
